
- hosts: all
  become: true
  tasks:

  - name: Create a directory to store pcap file
    ansible.builtin.file:
      path: /home/jhnrnzmendoza/pcapfiles
      state: directory

  - name: Copy pcap file from control node to managed node
    copy:
      src: /home/jhnrnzmendoza/MendozaHOA8/pcap1.pcap
      dest: /home/jhnrnzmendoza/pcapfiles/

  - name: Extract executable from pcap file
    shell:
      cmd: "tcpflow -r /home/jhnrnzmendoza/pcapfiles/pcap1.pcap -c port 80"
